name: IBM Cloud Auto deploy 
 
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 14 * * ?'

jobs:
  ibm20200620:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT3 }}
        REGION_NUM: ${{ secrets.REGION_NUM3 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME3 }}
        IBM_UUID: ${{ secrets.UUID }}
        IBM_PATH: ${{ secrets.PATH }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/$IBM_UUID/g'  v2ray/config.json
        #sed -i 's:/:$PATH:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME3 }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID3 }}
      run: |
        pwd
        #./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud target --cf-api  https://api.us-south.cf.cloud.ibm.com 
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
        
  ibm20200628:
    needs: ibm20200620
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g'  /v2ray/config.json
        #sed -i 's:/:${{ secrets.PATH }}:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
      run: |
        pwd
        #./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
        
  ibm20200708:
    needs: ibm20200628
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT1 }}
        REGION_NUM: ${{ secrets.REGION_NUM1 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME1 }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g'  /v2ray/config.json
        #sed -i 's:/:${{ secrets.PATH }}:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME1 }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID1 }}
      run: |
        pwd
        #./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
     
  ibm20200709:
    needs: ibm20200708
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT2 }}
        REGION_NUM: ${{ secrets.REGION_NUM2 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME2 }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g'  /v2ray/config.json
        #sed -i 's:/:${{ secrets.PATH }}:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME2 }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID2 }}
      run: |
        pwd
        #./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
        
  ibm20200712:
    needs: ibm20200709
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT4 }}
        REGION_NUM: ${{ secrets.REGION_NUM4 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME4 }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g'  /v2ray/config.json
        #sed -i 's:/:${{ secrets.PATH }}:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME4 }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID4 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
        
  ibm20200725:
    needs: ibm20200712
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT5 }}
        REGION_NUM: ${{ secrets.REGION_NUM5 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME5 }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g'  /v2ray/config.json
        #sed -i 's:/:${{ secrets.PATH }}:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME5 }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID5 }}
      run: |
        pwd
        #./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
        
  ibm20200731:
    needs: ibm20200725
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT6 }}
        REGION_NUM: ${{ secrets.REGION_NUM6 }}
      run: |
        pwd
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME6 }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g'  /v2ray/config.json
        #sed -i 's:/:${{ secrets.PATH }}:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME6 }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID6 }}
      run: |
        pwd
        #./IBM_Cloud_CLI/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install
        ./IBM_Cloud_CLI/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
               
