name: IBM Cloud Auto deploy 
 
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 14 * 7 ?'

jobs:
  ibm20200620:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        pwd
        ls
        unzip IBM_Cloud_CLI1.zip
        chmod -R 777 ./IBM_Cloud_CLI1/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        pwd
        ./IBM_Cloud_CLI1/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: deploy
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
        IBM_UUID: ${{ secrets.UUID }}
        IBM_PATH: ${{ secrets.PATH }}
      run: |
        pwd
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        chmod +x v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i 's/GetStartedGo/$IBM_APP_NAME/g'  manifest.yml
        #sed -i 's/8c35bef3-d51f-41ab-ac87-7b053410495b/$IBM_UUID/g'  v2ray/config.json
        #sed -i 's:/:$PATH:' /v2ray/config.json
        sed -i 's/128/256/g'  manifest.yml
    - name: Target IBM Cloud
      env:
       IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}      
       RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
      run: |
        pwd
        ./IBM_Cloud_CLI1/ibmcloud -v
        #./IBM_Cloud_CLI1/ibmcloud target -r eu-gb
        ./IBM_Cloud_CLI1/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI1/ibmcloud cf install
        ./IBM_Cloud_CLI1/ibmcloud target --cf
        ./IBM_Cloud_CLI1/ibmcloud cf push "$IBM_APP_NAME" -f v2ray-cloudfoundry/manifest.yml
        
